TradeTrust/tradetrust-utils

.github/workflows/release.yml

- Updated the CI-CD branch to master

fix: update ci-cd config

---

package.json
src/fragments/fragments.ts
src/index.ts

fix type error and expose constant error message and types
- fix type error as it is not pointing to the correct build file
- expose the constants error messages and expose constants types

fix: update build type error and expose constant error messages and types

---

src/constants/VerificationErrorMessages.ts

Added invalid network messages for invalid network scenario.
- Added invalid network messages for invalid network scenario.

feat: added error message for invalid network

---

src/constants/VerificationErrorMessages.ts

- What are the changes made in this pull request?
- Change this and that, etc...
What are the related issues or stories?

fix: update network error message

---

src/analytics/analytics.test.ts
src/analytics/analytics.ts

- simple check to make sure ga library is defined in global scope

fix: ga check

---

src/constants/SupportedNetworks.ts
src/index.ts

used several places, looking to consolidate it here
- export supported networks

feat: supported networks

---

src/constants/supportedChains.test.ts

test: chain info

---

src/constants/supportedChains.ts

Updated RPC URL for XDC network on mainnet and testnet.
Updated the configuration files containing RPC URLs.

Updated RPC for XDC Network

---

package-lock.json
package.json
src/constants/network.ts
src/constants/supportedChains.test.ts
src/constants/supportedChains.ts

add support for Polygon Amoy testnet
- network.ts to include polygon amoy testnet
- updated tt-verify package
- added dotenv package for secrets management
- added test for amoy chain details
- added polygon amoy to supported chain

feat: add amoy testnet

---

src/constants/network.ts
src/constants/supportedChains.test.ts
src/constants/supportedChains.ts

This PR adds support for Stability [Global Trust Network](https://github.com/stabilityprotocol/) network.
* supportedChains
* networks
NA

feat: add stability network to supported chains

---

package-lock.json
package.json

fix: update tt-verify

---

package-lock.json
package.json
src/constants/supportedChains.test.ts
src/constants/supportedChains.ts

update astron network info and test file
update:
package-lock.json
package.json
src/constants/supportedChains.test.ts
src/constants/supportedChains.ts

fix: update astron network info and test file

---

.github/workflows/linters.yml
.github/workflows/pull_requests.yml
.github/workflows/release.yml
.github/workflows/tests.yml
commitlint.config.js
package.json

- Add support for node 20
- What are the changes made in this pull request?
- Updated CI and package engine.

fix: add node 20 support

---

package.json

- Update exports to list all export paths

fix: update exports

---

package-lock.json
package.json

fix: type export error

---

package-lock.json
package.json
src/constants/supportedChains.ts
src/gasStation/index.ts
src/index.ts

- Copy gas station value into this repo, copy from tradetrust-core.

fix: copy gas station into utils

---

package-lock.json
package.json
src/gasStation/index.test.ts

- Add missing ethers package and test for gas station

fix: add missing ethers pkg

---

package-lock.json
package.json

fix: upgrade ethers

---

src/constants/VerificationErrorMessages.ts

feat: trigger build

---

package-lock.json
package.json
src/constants/network.ts
src/constants/supportedChains.test.ts
src/constants/supportedChains.ts

What is the background of this pull requests?
add astrontestnet network

feat: add astrontestnet network

---

src/constants/supportedChains.ts

update supported network RPC urls

chore: update supported networks
